### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [LFeh/piano#17]
Hi,
I have read your work so I decided to creat a logo for you. I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

Greetings

**Comment by nunojesus** [comment]
You want that format, but something about Piano, right?

**Comment by LFeh** [comment]
Exactly 😸

**Comment by nunojesus** [comment]
Do you want something like a piano, or something more abstract?

**Comment by nunojesus** [comment]
The name of the project it´s Piano? or something different?

**Comment by LFeh** [comment]
Just **Piano** or **Piano Keyboard**, hahahha

**Comment by nunojesus** [comment]
Hello, here is the logo that I design for you, see if you like it.

![pia](https://user-images.githubusercontent.com/34600369/39779935-9b89c97c-5302-11e8-9a69-857f994e617d.png)

**Comment by LFeh** [comment]
Can you change the red color on first logo to `#0291a7` or other blue pallet?

A love it 😄 

Congratulations

**Comment by nunojesus** [comment]
Is this color that you want? It looks good.
I will create a logo and a logotype with text, what do you prefer the 1st one or the 2nd?

![piano](https://user-images.githubusercontent.com/34600369/39818145-1fffd828-5398-11e8-9b96-6b6a438b11bc.png)

**Comment by LFeh** [comment]
Thanks @nunojesus. My others projects have logos (I think), hahaha

**Comment by nunojesus** [comment]
So I think I finish my work with this project, I will send you also a link with the editable logo files.

Do you have other project for me? I like the 1500-translator :)
If you know some friend that have opensource and want a logo just tell my name to them.

greetings!

**Comment by LFeh** [comment]
@nunojesus I've liked the `1500-translator`'s logo, hahaha

Maybe... [Front-end Challenges](https://github.com/LFeh/frontend-challenges)?

**Comment by Baptista949** [comment]
thank you very much, it is a  great job what you did.
But, could you creat one with my name "Baptista"?

2018-05-14 19:40 GMT+01:00 Felipe Fialho <notifications@github.com>:
