### ISSUE TITLE
Hello sir, I'm a graphic designer

### ISSUE THREAD

**Issue by rezarezz** [LFeh/piano#20]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by JoseCage** [comment]
Sorry if it sounds like a spam. @rezarezz can you also help my project (open source and free platform for blood donors) called @doesangueorg with design stuffs, sure.

**Comment by LFeh** [comment]
Hi @rezarezz, how are you?

I love your iniciative, but @nunojesus made it for [this project in the last week](https://github.com/LFeh/piano/issues/17).

Here have a lot of open-source projects that you can help.

https://github.com/frontendbr/open-source

Thanks again!
